# Generated by Django 5.2.12 on 2026-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='ai_suggested_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
