# Generated by Django 5.2.12 on 2026-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attemptanswer_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='available_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
